enchance

diff --git a/.github/workflows/actions/ado_tag/action.yml b/.github/workflows/actions/ado_tag/action.yml
--- a/.github/workflows/actions/ado_tag/action.yml
+++ b/.github/workflows/actions/ado_tag/action.yml
@@ -18,11 +18,25 @@ runs:
       env:
         GH_TOKEN: ${{ inputs.gh-token }}
       run: |
-        PRBODY=$(gh pr list --json body --repo ${{ inputs.repository }} --state all --search ${{ inputs.commit-sha }} --jq '.[].body')
+        PRBODY=$(gh pr list --json body --repo ${{ inputs.repository }} --state merged --search ${{ inputs.commit-sha }} --jq '.[].body')
         echo "PRs body: $PRBODY"
         echo "PRBODY=${PRBODY}" >> $GITHUB_ENV
       shell: bash
     - name: Extract work item reference number from PR's body
       id: extract-reference-number
-      run: echo "$PRBODY" | sed -n "s/^.*AB#\([0-9]*\).*$/\1/p"
+      run: |
+        reference_num=$(echo $PRBODY | sed -n "s/^.*AB#\([0-9]*\).*$/\1/p")
+        if [ -z "$reference_num" ]
+        then
+          echo "Reference number not found!"
+          exit 1
+        else
+          echo "Reference number is $reference_num"
+          echo "REFERENCE=${reference_num}" >> $GITHUB_ENV
+        fi
+      shell: bash
+    - name: Add env tag for workitem
+      id: tag-workitem
+      run: |
+        echo "$REFERENCE"
       shell: bash
